column_width = 120
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "olumn_width = 120
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreAutoPreferDouble"
call_parentheses = "None"
